"""Add academic_year to users

Revision ID: 1a455194ba69
Revises: 96d2ee27f48d
Create Date: 2025-12-03 21:57:49.745735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a455194ba69'
down_revision = '96d2ee27f48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('stopped_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['teacher_id'], ['id'])

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('subjects_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('academic_year')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('subjects_ibfk_2'), 'users', ['teacher_id'], ['id'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stopped_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
