"""Add password reset tokens table

Revision ID: 75b025719042
Revises: b8e872dd7b13
Create Date: 2025-12-02 16:46:39.516571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b025719042'
down_revision = 'b8e872dd7b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_dept_head', 'users', ['head_id'], ['id'], use_alter=True)

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_track_head', 'users', ['head_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_track_head', type_='foreignkey')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dept_head', type_='foreignkey')

    # ### end Alembic commands ###
